Added TWS parsing alongside some basic tests
TheGLander/tworld3 pull request #4
Opened 2024-09-25 03:11 UTC by SicklySilverMoon

2026-02-24 18:31 UTC, TheGLander requested changes
Code's mostly fine, thanks for finding the time to work on this!

2026-02-24 18:31 UTC, zyudneko commented on libchips/src/format-ccl.c
>  }
If this is now used in multiple files, the definition should be moved somewhere common too. Maybe `static inline` in formats.h or misc.h/misc.c, up to you

2026-02-24 18:31 UTC, zyudneko commented on libchips/src/format-tws.c
> +  if (self == NULL)
`NULL` checks aren't necessary for `free`

2026-02-24 18:31 UTC, TheGLander commented on libchips/src/format-tws.c
> +  self->solutions_n++;
`+= 1`

2026-02-24 18:31 UTC, zyudneko commented on libchips/src/format-tws.c
> +  if (self->solutions_n + 1 > self->solutions_allocated) {
We probably should have a generic vector struct (like in `libnotcc`) instead of replicating vector logic everywhere we need it. Okay for now I suppose, I'll port over that code later

2026-02-24 18:31 UTC, zyudneko commented on libchips/src/format-tws.c
> +Result_TWSSetPtr get_error(TWSSet* self, const char* err_msg) {
`static`?

2026-02-24 18:31 UTC, TheGLander commented on libchips/src/format-tws.c
> +  }
Are there overflow issues with just `return lsh->level_num - rhs->level_num`?

2026-02-24 18:31 UTC, zyudneko commented on libchips/src/format-tws.c
> +    for (uint32_t i = 0; i < self->solutions_n; i++) {
`+= 1`

2026-02-24 18:31 UTC, zyudneko commented on libchips/src/format-tws.c
> +  for (uint16_t i = 0; i < self->solutions_n; i++) {
`+= 1`

2026-02-24 18:31 UTC, zyudneko commented on libchips/src/format-tws.c
> +  //https://www.muppetlabs.com/~breadbox/software/tworld/tworldff.html#3
Remove leading spaces, add space after `//` (applies to all comments)

2026-02-24 18:31 UTC, zyudneko commented on libchips/src/format-tws.c
> +      size -= 16;
Should probably advance `data` once

2026-02-24 18:31 UTC, TheGLander commented on libchips/src/format-tws.c
> +    }
Move `assert_data_avail` inside the loop

2026-02-24 18:31 UTC, TheGLander commented on libchips/src/format-tws.c
> +        assert(((GameInput) DIRECTION_NIL) == 0);
`static_assert`?

2026-02-24 18:31 UTC, zyudneko commented on libchips/test/ccl/format-ccl.cpp
> +char const* titles[] = {
Should only have one array of string + time pair structs

2026-02-24 18:31 UTC, zyudneko commented on libchips/test/ccl/format-ccl.cpp
> +const uint8_t CCLP1_ccl[] = {
Don't we already have this in `ccl_embeds.h`?

2026-02-24 18:31 UTC, zyudneko commented on libchips/test/ccl/format-ccl.cpp
> +    EXPECT_EQ(set->levels_n, 149);
Duplicate line?

2026-02-24 18:31 UTC, zyudneko commented on libchips/test/data/ccl/ccl_embeds.h
> +#endif //LIBCHIPS_CCL_EMBEDS_H
EOF newline pls

2026-02-24 18:31 UTC, zyudneko commented on libchips/test/logic/cclp1_tws_playthrough.cpp
> +    Result_LevelSetPtr res = parse_ccl(CCLP1_ccl, sizeof(CCLP1_ccl));
1. In the future I'd like to have a CLI for running any CCL with any TWS (like I have with `libnotcc` and its CLI), but for now this is fine to have.
2. Please split the boilerplate into a function. You're missing some `*_free`s in the Lynx code, but the generic function will fix that.

2026-02-24 18:31 UTC, zyudneko commented on libchips/test/logic/cclp1_tws_playthrough.cpp
> +        ms_logic.tick_level(level);
Use `Level_tick`, it has some extra logic

2026-02-24 18:31 UTC, zyudneko commented on libchips/test/tws/format-tws.cpp
> +}
EOL newline pls

2026-02-24 18:31 UTC, zyudneko commented on libchips/test/CMakeLists.txt
> +include_directories(../src) #allow referencing source as if we were in the src dir
Okay, but note for me - we should split (public) header files into separate `include` dir

2026-02-24 18:31 UTC, zyudneko commented on libchips/test/CMakeLists.txt
> +file(GLOB_RECURSE GLOB_SRCS ../src/*.h ../src/*.c ../src/*.cpp)
We should link with `libchips` library, not build with its source

2026-02-24 18:41 UTC, SicklySilverMoon commented on libchips/src/format-tws.c
> +  }
Potentially yes, as I believe the TWS format allows the full `uint16_t` range, as well as unsigned subtraction to signed

2026-02-24 18:42 UTC, SicklySilverMoon commented on libchips/src/format-tws.c
> +      size -= 16;
Going to request elaboration on what you specifically mean by this one please

2026-02-24 18:43 UTC, zyudneko commented on libchips/src/format-tws.c
> +      size -= 16;
`data += 16;` instead of the split `+= 10` and `+= 6`

2026-02-24 18:57 UTC, zyudneko commented on libchips/src/format-tws.c
> +  }
Okay, I suppose it can be left as-is

2026-02-26 04:46 UTC, SicklySilverMoon commented
Requesting review again, although at present loading a TWS file preloads all possible moves, I've made changes to many places such as logic (as I got ahead of myself) and would greatly prefer to not have to start reconciling in the event of further updates to the main branch

2026-02-28 20:38 UTC, TheGLander requested changes

2026-02-28 20:38 UTC, zyudneko commented on libchips/src/format-tws.c
> +        level.compressed_inputs = xmalloc(sizeof(CompressedInputList));
I don't think we should be dynamically allocating this. I understand this is probably to make it clearly nullable, but I think we should represent that differently somehow (maybe a Rust-like `Opt` union, or a null `bytes` pointer representing no value?)

2026-02-28 20:38 UTC, zyudneko commented on libchips/src/format-tws.c
> +    self->inputs = xrealloc(self->inputs, sizeof(GameInput) * self->allocated);
Should just set `count` without reallocating, user can use `shrink` when they know they aren't gonna be appending any more

2026-02-28 20:38 UTC, zyudneko commented on libchips/src/format-tws.c
> +    self->inputs = xrealloc(self->inputs, sizeof(GameInput) * self->allocated);
Should follow same reallocation logic as resizing in `append` (which should be split to a separate helper function)

2026-02-28 20:38 UTC, TheGLander commented on libchips/src/format-tws.c
> +    }
`static_assert(DIRECTION_NIL == 0)` + `memset`?

2026-02-28 21:38 UTC, TheGLander approved these changes

2026-03-01 01:40 UTC, SicklySilverMoon commented
Now that commits have been squashed into one using the above (see full original history at [https://github.com/SicklySilverMoon/tworld3/tree/pr-tws](https://github.com/SicklySilverMoon/tworld3/tree/pr-tws)), it is being merged.

2026-03-01 01:40 UTC, merged